name: verify
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.19.1'
      - run: corepack enable && yarn set version 1.22.22
      - run: yarn install --frozen-lockfile
      - run: yarn verify